apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spring-app-replica
  labels:
    app: demo-spring-app
    name: spring-app-replica
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-spring-app
      name: spring-app
  template:
    metadata: 
      name: spring-app
      labels:
        app: demo-spring-app
        name: spring-app
    spec:
      containers:
        - name: spring-app
          image: docker.local/springapp
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
