apiVersion: v1
kind: Service
metadata: 
  name: spring-app-service
  labels:
    app: demo-spring-app
    name: spring-app-service
spec:
  type: NodePort
  selector:
    app: demo-spring-app
    name: spring-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

